# 1.4.4 Smoothing Images

## Kernel Convolution

In [3]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [4]:
l=1
kernel = np.array([[0,-1,0],[-1,4,-1],[0,-1,0]],np.float32)

In [5]:
kernel

array([[ 0., -1.,  0.],
       [-1.,  4., -1.],
       [ 0., -1.,  0.]], dtype=float32)

In [6]:
img = np.random.randint(10, size=(12,12))
#img = np.ones((10,10),np.float32)

In [7]:
img

array([[2, 9, 9, 7, 9, 2, 0, 9, 2, 5, 3, 1],
       [8, 1, 7, 7, 2, 1, 6, 4, 8, 1, 9, 3],
       [3, 4, 4, 8, 1, 2, 5, 7, 6, 1, 7, 1],
       [6, 8, 1, 9, 5, 6, 9, 3, 4, 9, 9, 3],
       [2, 5, 8, 5, 2, 4, 4, 9, 8, 0, 5, 6],
       [9, 8, 5, 1, 1, 1, 0, 2, 2, 1, 2, 1],
       [7, 2, 6, 4, 7, 6, 8, 2, 0, 7, 9, 0],
       [6, 5, 3, 8, 7, 7, 2, 8, 3, 9, 5, 4],
       [3, 2, 9, 7, 9, 9, 2, 7, 1, 5, 4, 5],
       [2, 0, 6, 1, 8, 5, 4, 6, 2, 3, 7, 3],
       [0, 4, 4, 1, 8, 5, 3, 1, 0, 0, 7, 9],
       [3, 0, 1, 4, 2, 3, 5, 8, 8, 4, 9, 6]])

In [8]:
h,w=img.shape

In [9]:
print(h,w)

12 12


In [10]:
#[*range(-2,3)]

In [11]:
dst = np.zeros((h,w),np.int)

/var/folders/g7/dh8v6rd91kz0fm7zl5kcjvq40000gn/T/ipykernel_51364/2160328971.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dst = np.zeros((h,w),np.int)


In [12]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i,j]=t        

In [13]:
img

array([[2, 9, 9, 7, 9, 2, 0, 9, 2, 5, 3, 1],
       [8, 1, 7, 7, 2, 1, 6, 4, 8, 1, 9, 3],
       [3, 4, 4, 8, 1, 2, 5, 7, 6, 1, 7, 1],
       [6, 8, 1, 9, 5, 6, 9, 3, 4, 9, 9, 3],
       [2, 5, 8, 5, 2, 4, 4, 9, 8, 0, 5, 6],
       [9, 8, 5, 1, 1, 1, 0, 2, 2, 1, 2, 1],
       [7, 2, 6, 4, 7, 6, 8, 2, 0, 7, 9, 0],
       [6, 5, 3, 8, 7, 7, 2, 8, 3, 9, 5, 4],
       [3, 2, 9, 7, 9, 9, 2, 7, 1, 5, 4, 5],
       [2, 0, 6, 1, 8, 5, 4, 6, 2, 3, 7, 3],
       [0, 4, 4, 1, 8, 5, 3, 1, 0, 0, 7, 9],
       [3, 0, 1, 4, 2, 3, 5, 8, 8, 4, 9, 6]])

In [14]:
dst

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0, -24,   7,   4, -10,  -8,  14, -14,  19, -19,  22,   0],
       [  0,   0,  -4,  11, -13,  -5,  -4,  10,   4, -19,   8,   0],
       [  0,  16, -25,  17,   2,   4,  18, -17, -10,  22,  12,   0],
       [  0,  -6,  16,   0,  -7,   3,  -6,  19,  17, -23,   3,   0],
       [  0,  11,  -3, -11,  -7,  -7, -15,  -5,  -3,  -7,  -8,   0],
       [  0, -18,  10,  -6,  10,   1,  22, -10, -14,   9,  22,   0],
       [  0,   7, -16,  11,  -3,   4, -17,  18,  -6,  16,  -6,   0],
       [  0,  -9,  18,   1,   5,  13, -14,  11, -13,   3,  -6,   0],
       [  0, -14,  10, -18,   9,  -6,   0,  10,  -2,  -2,  11,   0],
       [  0,  12,   4, -13,  16,   1,  -3, -13, -11, -14,   3,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [15]:
img = cv2.imread('/Users/hwangseho/Desktop/IP_2022/lena.png', 0)

In [16]:
h,w = img.shape

In [17]:
dst = np.zeros((h-2*l,w-2*l),np.uint8)

In [18]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i-l,j-l]=t 

In [19]:
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()